version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: wms-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-wms}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: wms-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: wms-api
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgresdb}@${POSTGRES_HOST:-postgres}:5432/${POSTGRES_DB:-wms}?schema=public
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-minio}
      - MINIO_PORT=${MINIO_PORT:-9000}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin}
      - MINIO_BUCKET=${MINIO_BUCKET:-wms-bucket}
      - MINIO_USE_SSL=${MINIO_USE_SSL:-false}
      - MINIO_PUBLIC_URL=${MINIO_PUBLIC_URL:-"http://localhost:9000"}
      - JWT_SECRET=${JWT_SECRET:-super-secret-bulog-wms-key}
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-465}
      - SMTP_USER=${SMTP_USER:-[EMAIL_ADDRESS]'}
      - SMTP_PASS=${SMTP_PASS:-gjrg nudt haqr mygw}
      - SMTP_SECURE=${SMTP_SECURE:-true}
      - SMTP_FROM=${SMTP_FROM:-"Bulog WMS" <[EMAIL_ADDRESS]'}
      - FRONTEND_URL=${FRONTEND_URL:-"http://localhost:3001"}
      - PORT=${PORT:-3002}
    ports:
      - "${PORT:-3002}:${PORT:-3002}"
    dns:
      - 10.254.250.27
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2024-01-28T22-35-53Z
    container_name: wms-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      MINIO_SERVER_URL: ${MINIO_PUBLIC_URL:-"http://localhost:9000"}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL:-"http://localhost:9090"}
    ports:
      - "9000:9000"
      - "9090:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: wms-web
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-"http://localhost:3002/api"}
      - PORT=${PORT:-3001}
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  minio_data:
